[build]
  command = "sed -e 's/__AT_TOKEN__/'\"$AT_TOKEN\"'/g' -e 's/__OAI_KEY__/'\"$OAI_KEY\"'/g' index.html > index.built.html && mv index.built.html index.html"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "AT_TOKEN,OAI_KEY"
